name: PR Validate

on:
  pull_request: 
    branches: ['main', 'master']

  push:
    branches: ['main', 'master']

jobs:
  not-configured:
    if: vars.FABRIC_APPLICATION_ID == ''
    name: Not configured
    runs-on: ubuntu-latest

    steps:
      - run: echo "Fabric Application ID not found."

  validate:
    if: vars.FABRIC_APPLICATION_ID != ''
    name: Build and test
    uses: ey-fabric/fabric-workflow-shared/.github/workflows/workflow_python-validate.yml@v3
    with:
      python_version: ${{ vars.PYTHON_VERSION }}
      project_name: ${{ vars.PROJECT_NAME }}
      continue-on-sonar-error: "true"
      test_folder: ${{ vars.TEST_FOLDER }}
      sonarqube_sources: ${{ vars.SONARQUBE_SOURCES }}
      sonarqube_host: ${{ vars.SONAR_HOST_URL }}
      fabric_application_api_url: ${{ vars.FABRIC_APPLICATION_API_URL }}
      fabric_application_id: ${{ vars.FABRIC_APPLICATION_ID }}
      artifactory_helm_url: ${{ vars.JFROG_HELM_REPO_DEV }}
      registry_url: ${{ vars.JFROG_DOCKER_REGISTRY_SERVER_NAME_DEV }}
      apm-id: ${{ vars.APM_ID }}
      spr-id: ${{ vars.SPR_ID }}
      portfolio: ${{ vars.PROJECT_PORTFOLIO }}
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ARTIFACTORY_USERNAME: ${{ vars.JF_USER }}
      ARTIFACTORY_TOKEN: ${{ secrets.JF_PASS }}
      REGISTRY_USERNAME: ${{ vars.JF_USER }}
      REGISTRY_TOKEN: ${{ secrets.JF_PASS }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      TENANT_ID: ${{ vars.TENANT_ID }}
      CLIENT_ID: ${{ secrets.PUBLISH_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.PUBLISH_CLIENT_SECRET }}
      SCOPE: ${{ secrets.PUBLISH_SCOPE }}
      CHECKMARX_USERNAME: ${{ vars.CHECKMARX_USERNAME }}
      CHECKMARX_PASSWORD: ${{ secrets.CHECKMARX_PASSWORD }}
      MEND_ACTION_STS: ${{ secrets.MEND_ACTION_STS }}
      ARCHER_SPR_API_TOKEN: ${{ secrets.ARCHER_SPR_API_TOKEN }}
      INFOSEC_CONNECTIONKEY: ${{ secrets.INFOSEC_CONNECTIONKEY }}
      NULLPLATFORM_API_KEY: ${{ secrets.NULLPLATFORM_API_KEY }}
      GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}

  check:
    name: Check
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: echo "All checks passed"

  release:
    name: Release
    needs: check
    if: github.event_name == 'push'
    uses: ey-fabric/fabric-workflow-shared/.github/workflows/workflow_python-release.yml@v3
    secrets:
      GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}

