name: Publish assets

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish artifacts
    uses: ey-fabric/fabric-workflow-shared/.github/workflows/workflow_javascript-publish.yml@v3
    with:
      node_version: ${{ vars.NODE_VERSION }}
      sonarqube_host: ${{ vars.SONAR_HOST_URL }}
      fabric_application_api_url: ${{ vars.FABRIC_APPLICATION_API_URL }}
      fabric_application_id: ${{ vars.FABRIC_APPLICATION_ID }}
      artifactory_helm_url: ${{ vars.JFROG_HELM_REPO_URL_DEV }}
      artifactory_generic_url: ${{ vars.JFROG_GENERIC_REPO_URL_DEV }}
      registry_url: ${{ vars.JFROG_DOCKER_REGISTRY_SERVER_NAME_DEV }}
      npm_mfe_registry_url: ${{ vars.JFROG_NPM_MFE_REGISTRY_URL }}
      npm_mfe_username: ${{ vars.JFROG_NPM_USER_MFE }}
      npm_mfe_email: ${{ vars.JFROG_NPM_EMAIL_MFE }}
      npm_motif_registry_url: ${{ vars.JFROG_NPM_MOTIF_REGISTRY_URL }}
      npm_motif_username: ${{ vars.JFROG_NPM_USER_MOTIF }}
      npm_motif_email: ${{ vars.JFROG_NPM_EMAIL_MOTIF }}
    secrets:
      NPM_MFE_PASSWORD: ${{ secrets.JFROG_NPM_TOKEN_MFE }}
      NPM_MOTIF_PASSWORD: ${{ secrets.JFROG_NPM_TOKEN_MOTIF }}
      NULLPLATFORM_API_KEY: ${{ secrets.NULLPLATFORM_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ARTIFACTORY_USERNAME: ${{ vars.JF_USER }}
      ARTIFACTORY_TOKEN: ${{ secrets.JF_PASS }}
      TENANT_ID: ${{ vars.TENANT_ID }}
      CLIENT_ID: ${{ secrets.PUBLISH_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.PUBLISH_CLIENT_SECRET }}
      SCOPE: ${{ secrets.PUBLISH_SCOPE }}
      GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
